FileAction:
- atom:
  - hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
- vim:
  - hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
- vimrc:
  - hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
