Globals:
  exitOnError: true
  confirmEveryPackage: true

includes:
  - common_system.yml
  - editors.yml
  - tmux.yml

FileAction:
  aliases:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$
  bashrc:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$
  exports:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$

PackageAction:
  i3:
    alternatives: i3wm
