FileAction:
- dunst:
  - hidden: false
    source: ../common
    command: ln -s
    destination: $HOME/.config
- i3:
  - hidden: false
    source: ../common
    command: ln -s
    destination: $HOME/.config
- rofi: # not sure about this...seems broken the way it is configured
  - hidden: false
    source: ../common/i3
    command: ln -s
    destination: $HOME/.config
- xinitrc:
  - hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
- Xmodmap:
  - hidden: true
    source: ../common
    command: ln -s
    destination: $HOME
