FileAction:
  tmux.conf:
    hidden: true
    source: ../common
    command: ln -s
    destination: $#HOME#$
  tmux.theme.sh:
    hidden: true
    source: ../common
    command: ln -s
    destination: $#HOME#$
  tmux-resurrect:
    hidden: true
    source: ../common
    command: ln -s
    destination: $#HOME#$

PackageAction:
  - name: i3
  - name: tmux-resurrect
    source: git
    url: https://github.com/tmux-plugins/tmux-resurrect.git
    destination: $#HOME#$/.tmux-resurrect
