Globals:
- exitOnError: true
  confirmEveryPackage: true

includes:
  - common_system.yml
  - editors.yml

FileAction:
- aliases:
  - hidden: true
    source: ../work
    command: ln -s
    destination: $HOME
- exports:
  - hidden: true
    source: ../work
    command: ln -s
    destination: $HOME
- k8s_setup:
  - hidden: true
    source: ../work
    command: ln -s
    destination: $HOME
- tmuxinator:
  - hidden: true
    source: ../work
    command: ln -s
    destination: $HOME

PackageAction:
- i3:
  - alternatives: i3wm
