FileAction:
  xfce4:
    hidden: false
    source: ../common
    command: ln -s
    destination: $#HOME#$/.config
  devilspie2:
    hidden: true
    source: ../common
    command: ln -s
    destination: $#HOME#$


PackageAction:
  wmctrl:
    alternatives: wmctrl
